Updated index.js to fix 2 footer bug
keploy/docs pull request #149
Opened 2023-03-05 10:21 UTC by Nayanika-12

Closes https://github.com/keploy/keploy/issues/320

Two footers are present on several documentation pages. I tried fixing the issue. Please take a look.

2023-03-05 11:08 UTC, Nayanika-12 commented
Closes https://github.com/keploy/keploy/issues/320

Two footers are present on several documentation pages. I tried fixing the issue. Please take a look.

Signed-off-by Nayanika-12 [nayanikasc2002@gmail.com](mailto:nayanikasc2002@gmail.com)

2023-03-05 13:08 UTC, nehagup requested changes
@Nayanika-12 the issue still exists, have you tried running the fix locally?

2023-03-28 07:44 UTC, nehagup commented
@Nayanika-12 are you still working on this?

2023-05-24 13:11 UTC, kartikmehta8 commented
@nehagup This issue is resolved today with the PR [#175](https://github.com/keploy/docs/pull/175). You can close this PR now. :)

2023-05-25 05:10 UTC, closed without merging