Added typescript sample app to keploy docs repo
keploy/docs pull request #162
Opened 2023-03-29 10:56 UTC by mukul314

# Pull Request Template

## Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-03-30 01:14 UTC, mukul314 commented
@nehagup I have added the sample typescript app, please check and see if its okay.

2023-04-04 15:21 UTC, SanskritiHarmukh requested changes

2023-04-04 15:21 UTC, SanskritiHarmukh commented on docs/typescript/quickstart/node-fetch.md
> +
@mukul314 can you include the installation part here instead which you've added [here](https://github.com/keploy/docs/pull/162/files#diff-68f73088dc8486a51efc8eda10a3d5165a5173eaa8569e38c5656d0d17d5cd0cR25) like shown below.
![Screenshot from 2023-04-04 20-36-53](https://user-images.githubusercontent.com/74777863/229837937-ec5983d2-5d5f-420c-85bf-ef3a7c5ae475.png)

2023-04-04 15:21 UTC, SanskritiHarmukh commented on docs/typescript/quickstart/node-fetch.md
> +
@mukul314 can you include the installation part here instead which you've added [here](https://github.com/keploy/docs/pull/162/files#diff-68f73088dc8486a51efc8eda10a3d5165a5173eaa8569e38c5656d0d17d5cd0cR25) like shown below.
![Screenshot from 2023-04-04 20-36-53](https://user-images.githubusercontent.com/74777863/229837937-ec5983d2-5d5f-420c-85bf-ef3a7c5ae475.png)

2023-04-04 15:21 UTC, SanskritiHarmukh commented on docs/typescript/quickstart/node-fetch.md
> +
Can you include some images of keploy server when it shows the recorded test cases and mocks when API calls are made?

2023-04-04 15:21 UTC, SanskritiHarmukh commented on docs/typescript/quickstart/node-fetch.md
> +
Introducing a bug and failed test cases part is missing, can you figure that out ?

2023-11-17 04:12 UTC, closed without merging