feat: added Gorilla/Mux-SQL Sample
keploy/docs pull request #168
Opened 2023-04-11 13:37 UTC by SanjaySinghRajpoot

# Pull Request Template

## Description

Added Example of Gorilla/Mux-SQL. 

Fixes #513

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] This change requires a documentation update.

## Screen Shot
![image](https://user-images.githubusercontent.com/67458417/231180762-da3f33c0-7e60-43a6-a809-5d9e3b711243.png)

2023-04-11 14:07 UTC, nehagup commented
@developer-diganta can you please review?

2023-04-11 19:09 UTC, developer-diganta reviewed
Also overall, can you please change the URL Shortener mentions to Gorilla Mux SQL app since currently in quite a few places, it mentions URL Shortener app? Also please structure the Generate Tests part like the [URL Shortener  docs](https://docs.keploy.io/docs/go/quickstart/echo-sql/#test-mode). Also please add a small description of the app to ```quickstart.md```

2023-04-11 19:09 UTC, developer-diganta commented on docs/go/quickstart/gorillamux-sql.md
> +git clone https://github.com/keploy/samples-go && cd mux-sql
Can you please change the command to  ```git clone https://github.com/keploy/samples-go && cd samples-go/mux-sql```

2023-04-11 19:09 UTC, developer-diganta commented on docs/go/quickstart/gorillamux-sql.md
> +go run handler.go main.go
Can you please change this to ```go run  .```?

2023-04-12 09:06 UTC, SanjaySinghRajpoot commented on docs/go/quickstart/gorillamux-sql.md
> +go run handler.go main.go
ok

2023-04-12 09:06 UTC, SanjaySinghRajpoot commented on docs/go/quickstart/gorillamux-sql.md
> +git clone https://github.com/keploy/samples-go && cd mux-sql
Updated the code for latest changes.

2023-04-12 09:14 UTC, SanjaySinghRajpoot commented on docs/go/quickstart/gorillamux-sql.md
> +git clone https://github.com/keploy/samples-go && cd mux-sql
I have updated the quick start docs. There was a wrong description added to the heading I have also fixed it.

2023-04-12 19:06 UTC, developer-diganta requested changes
Hi @SanjaySinghRajpoot ! Have requested the changes. Do let me know if you face any issues!

2023-04-12 19:06 UTC, developer-diganta commented on docs/go/quickstart/gorillamux-sql.md
> +git clone https://github.com/keploy/samples-go && cd mux-sql
Hi @SanjaySinghRajpoot! I guess you have to add the ```samples/go``` to cd command as ```mux-sql``` would be a folder inside the cloned repo

2023-04-12 19:06 UTC, developer-diganta commented on docs/go/quickstart/gorillamux-sql.md
> +## Generate testcases
Please change the api calls as per [this](https://github.com/keploy/samples-go/tree/main/mux-sql). You can try these once by running the sample app and making the api calls with the appropriate end points.

2023-04-12 19:06 UTC, developer-diganta commented on docs/go/quickstart/gorillamux-sql.md
> +
Also please change these to ```Test Mode``` just like [this](https://docs.keploy.io/docs/go/quickstart/echo-sql#test-mode). Also can you please change something in the sample app of gorilla/mux-sql and then give a screenshot of the output of keploy detecting the diff in results?

2023-04-12 19:06 UTC, developer-diganta commented on docs/go/quickstart/quickstart.md
> +- [URL Shortener with Gorilla Mux SQL](/docs/go/quickstart/gorillamux-sql) - A sample URL Shortener app that responds with a shortened URL of the URL sent as a request. The application tests Keploy i
Can you also check as this would be a product catalogue app.

2023-04-12 19:06 UTC, developer-diganta commented on docs/go/quickstart/gorillamux-sql.md
> +# URL Shortener Sample App
The entire doc for this app would be a product catalogue app. You can try running the sample app! Do let me know if you face any issues!

2023-05-27 20:59 UTC, developer-diganta commented
@SanjaySinghRajpoot are you still working on this? Do let me know if you need any help!

2023-11-06 09:43 UTC, closed without merging