added meta-data and json-ld structured data
keploy/docs pull request #194
Opened 2023-09-13 01:52 UTC by ganeshrevadi

# Pull Request Template

## Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes (https://github.com/keploy/keploy/issues/803)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-09-13 06:19 UTC, nehagup reviewed
@ganeshrevadi Thanks for the PR. 

There are unnecessary linting changes like replacing '' with "" that are not relevant to this PR.

2023-09-13 06:19 UTC, nehagup commented on docusaurus.config.js
> +      {name: "keywords", content: "cooking, blog"},
keywords are not right and are directly copied from the sample given.

2023-09-13 06:19 UTC, nehagup commented on docusaurus.config.js
> +          href: "https://example.com",
Copy-pasted!

2023-09-13 14:07 UTC, ganeshrevadi commented
> @ganeshrevadi Thanks for the PR.
> 
> There are unnecessary linting changes like replacing '' with "" that are not relevant to this PR.

I have made the changes !

2023-09-16 08:01 UTC, nehagup requested changes
@ganeshrevadi there are still listing changes like - "" replaced with '' which are not related to this PR. Can you please revert those back and make the necessary changes only?

2023-09-16 09:08 UTC, ganeshrevadi commented
> @ganeshrevadi there are still listing changes like - "" replaced with '' which are not related to this PR. Can you please revert those back and make the necessary changes only?
Hey @nehagup ! I have created a new PR for the following changes 
(https://github.com/keploy/docs/pull/203)

2023-09-16 09:08 UTC, ganeshrevadi commented
Can this PR be closed?

2023-09-16 09:14 UTC, closed without merging

2023-09-16 09:14 UTC, Sonichigo commented
Closing this PR since new changes are in PR #203