fix: removed keep alive header term from dev guide
keploy/docs pull request #278
Opened 2023-12-06 15:30 UTC by Arindam200

## Description

I have removed keep alive header term from dev guide

Fixes # (issue)

## Type of change

Docs Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-12-07 04:57 UTC, nehagup approved these changes

2023-12-07 04:58 UTC, nehagup reviewed
@Arindam200 can you please remove keep-alive mentions at other places in the docs as well!?

2023-12-07 11:35 UTC, Arindam200 commented
> @Arindam200 can you please remove keep-alive mentions at other places in the docs as well!?

Yes! I'm working on that!

2023-12-10 04:07 UTC, nehagup commented on versioned_docs/version-2.0.0/quickstart/node-express-mongoose.md
> +  Our testcases failed because in test mode the Keploy uses the `Mocks.yml`, which was generated in the record mode. 🕰️
@Sonichigo is this statement still required?

2024-01-04 10:36 UTC, Sonichigo requested changes
Please modify the specified lines!

2024-01-04 10:36 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mongoose.md
> +  Our testcases failed because in test mode the Keploy uses the `Mocks.yml`, which was generated in the record mode. 🕰️
No, since the keep-alive support has been added this statement has turned redundant/unnecessary.

2024-01-05 09:49 UTC, nehagup approved these changes

2024-01-05 09:56 UTC, merged