docs for mysql app
keploy/docs pull request #305
Opened 2024-01-16 16:12 UTC by EraKin575

# Pull Request Template

## Description

sample app doc for mysql sample app

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-01-17 06:11 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  <img src="/docs/img/testrun-node-fail.png" alt="Sample Keploy Test Result Gin MongoDB" width="100%" style={{ borderRadius: '5px' }}/>
MongoDb is present instead of MySQL

2024-01-17 06:28 UTC, Sonichigo requested changes

2024-01-17 06:28 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  #### 🍃 Kickstart MongoDB
Here too:-

2024-01-17 06:28 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  <img src="/docs/img/testrun-node-pass.png" alt="Sample Keploy Test Result Node MongoDB" width="100%" style={{ borderRadius: '5px' }}/>
here as well

2024-01-17 06:28 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  <img src="/docs/img/testrun-node-fail.png" alt="Sample Keploy Test Result Gin MongoDB" width="100%" style={{ borderRadius: '5px' }}/>
image added is incorrect as well

2024-01-17 06:28 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  <img src="/docs/img/testrun-node-pass.png" alt="Sample Keploy Test Result Node MongoDB" width="100%" style={{ borderRadius: '5px' }}/>
same with here image is incorrect

2024-01-17 06:28 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  ````bash
Styling format is breaking 
![Uploading image.png…]()

2024-01-17 06:28 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  <img src="/docs/img/testrun-node-fail.png" alt="Sample Keploy Test Result Gin MongoDB" width="100%" style={{ borderRadius: '5px' }}/>
https://github.com/Sonichigo/samples-typescript/blob/main/js-mysql/keploy/test-set-0/tests/test-1.yaml

please update based on the actual output of the test results, `ts` is not present in this application.

2024-01-17 06:28 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  <img src="/docs/img/testrun-node-pass.png" alt="Sample Keploy Test Result Node MongoDB" width="100%" style={{ borderRadius: '5px' }}/>
```
Worry not, just add the ever-changing fields (like our ts here) to the noise parameter to dodge those assertions.

Sample Keploy Test Result Node sql
```
same here as well

2024-01-17 06:28 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  keploy record -c "docker compose up" --containerName "nodesqlapp"
https://github.com/Sonichigo/samples-typescript/blob/main/js-mysql/docker-compose.yaml

In the docker-compose.yml file the containerName is not present. there this method won't work unless add manually by user following the guide.

2024-01-17 06:28 UTC, Sonichigo commented on versioned_docs/version-2.0.0/quickstart/node-express-mysql.md
> +  keploy record -c "docker compose up" --containerName "nodesqlapp"
https://github.com/Sonichigo/samples-typescript/blob/main/js-mysql/docker-compose.yaml

In the docker-compose.yml file the containerName is not present. there this method won't work unless add manually by user following the guide.

2024-01-24 14:42 UTC, Sarthak160 commented
@EraKin575 Please update the PR with the requested review.

2024-01-30 19:07 UTC, Sarthak160 commented
@Sonichigo @EraKin575 Is this ready to merge ??

2024-01-31 09:14 UTC, merged