feat: Updated Keploy-config Documentation
keploy/docs pull request #308
Opened 2024-01-19 08:09 UTC by Arindam200

# Pull Request: 

## Description

This pull request enhances the documentation for Keploy-config to provide clearer explanations and examples for each configuration term. The goal is to improve user understanding and facilitate smoother usage of the Keploy-config YAML file.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] Documentation update.
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Additional Context

Screenshots/gifs: N/A

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-01-21 16:03 UTC, AkashKumar7902 reviewed
please address the review comments

2024-01-21 16:03 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +- **`tests`**: Mapping of test sets to specific tests.
make description more intituitve . replace it by "testset/testcase(s) to run".

2024-01-21 16:03 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +    "test-set-1": ["test-1", "test-2"]
add one more example. second one would demonstrate running an entire test set. 
`"test-set-2": []`

2024-01-21 16:03 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +- **`globalNoise`**: Global noise ignored for all API calls.
replace it with "noisy fields to be ignored at global/test-set level."

2024-01-21 16:03 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +    body: {"url": ["https?://\S+"]}
you can also add a noisy field in header.

2024-01-21 16:03 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +
replacing it with this seems better, wdyt ?
"Earlier the only way to add the [noisy fields](http://keploy.io/docs/concepts/general-glossary/#3-noisy-field) was by modifying individual test file (testcase level). Now, With the introduction of config file, users can add the noisy fields at test-set and global level through config file itself."

2024-01-29 11:49 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +              port: 0
the one I gave was a sample config, you can remove the hose from here

2024-01-29 11:49 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
>      coverageReportPath: ""
same here , tge reqres.in can be removed and replace with empty string

2024-01-29 11:49 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +        host: "reqres.in"
set host to be empty string

2024-01-29 11:49 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +  stubs:
this is a bypass for mocks calls

2024-01-29 11:49 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +  ```
this is removed from tests , tests field not used in tests anymore

2024-01-29 11:49 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +
same as for the stubs during record

2024-01-29 11:49 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +      port: 0
host to empty string

2024-01-29 11:49 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +
removed this flag 
![Uploading image.png…]()

2024-01-30 05:20 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +
this field is removed now this works under stubs port.

2024-01-30 05:20 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +  Example:
filters to record tests.

2024-01-30 05:27 UTC, shivamsouravjha commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +
also you can explain some more about port, path and host in stubs and filters

Like if you see this 
```    # Example on using tests
    # tests: 
    #   filters:
    #    - path: "/user/app"
    #      urlMethods: ["GET"]
    #      headers: {
    #        "^asdf*": "^test"
    #      }
    #      host: "dc.services.visualstudio.com"
    # Example on using stubs
    # stubs: 
    #   filters:
    #    - path: "/user/app"
    #      port: 8080
    #    - port: 8081
    #    - host: "dc.services.visualstudio.com"
    #    - port: 8081
    #      host: "dc.services.visualstudio.com"
    #      path: "/user/app"
    #
    # Example on using globalNoise```
    
    user must be told how these fields can be used together as well as independently

2024-02-01 17:19 UTC, AkashKumar7902 requested changes
please address the review comments

2024-02-01 17:19 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
>      apiTimeout: 5
add `ignoreOrdering` field. 
https://github.com/keploy/keploy/issues/1413

2024-02-01 17:19 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +
add description of `ignoreOrdering`

2024-02-01 17:19 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +The Global Noise section is used to define parameters that are globally ignored for all API calls during testing. It enables you to filter out consistent noise, ensuring a cleaner evaluation of respo
replace "The Global Noise section" to "The `global` subsection of `globalNoise`"

2024-02-01 17:19 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +  - **`body`**: Defines patterns to ignore for the request or response body, such as filtering out URLs. Example: `{"url": ["https?://\S+", "http://\S+"]}`
its only for response body, I believe

2024-02-01 17:19 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +  - **`body`**: Defines patterns to ignore for the request or response body within the specified test set. Example: `{"uuid": ["b464d6df-d28b-4d12-8af1-0e2d61289578"]}`
same here. only for response body

2024-02-01 17:19 UTC, AkashKumar7902 commented on versioned_docs/version-2.0.0/running-keploy/configuration-file.md
> +The Keploy-config file eliminates the need to repeatedly specify parameters for each record or test command. The parameters in the file correspond to the flags in the Keploy [CLI Command Docs](http:/
the last statement can be modified to :
"Using keploy-config can help reduce the record and test command to just:"

2024-02-01 18:05 UTC, AkashKumar7902 commented
LGTM

2024-02-01 18:06 UTC, AkashKumar7902 approved these changes

2024-02-01 18:23 UTC, shivamsouravjha approved these changes
LGTM

2024-02-09 10:25 UTC, merged