added deduplication docs
keploy/docs pull request #393
Opened 2024-05-14 16:11 UTC by EraKin575

# Pull Request Template

## Description

added deduplication docs

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-05-16 08:04 UTC, Sonichigo requested changes

2024-05-16 08:04 UTC, Sonichigo commented on versioned_docs/version-2.0.0/keploy-cloud/deduplication.md
> +<<<<<<< HEAD
hi @EraKin575 please remove the commit messages from the docs

2024-05-16 08:04 UTC, Sonichigo commented on versioned_docs/version-2.0.0/keploy-cloud/deduplication.md
> +> > > > > > > d9e9a18a1c3b58d557559c5a734a5e1cc0121eab
here also

2024-05-17 11:45 UTC, Sonichigo requested changes

2024-05-17 11:45 UTC, Sonichigo commented on versioned_sidebars/version-2.0.0-sidebars.json
>        ]
url for auto-test-generation is missing from the here.

2024-06-21 11:39 UTC, nehagup approved these changes

2024-06-21 11:39 UTC, merged